translator_tables = {
    #mục column table
        "ID": "ID",
        "論理名": "tên logic",
        "物理名": "tên vật lý",
        "データ型": "kiểu dữ liệu",
        "デフォルト": "default",
        "アクセス日時": "アクセス日時 (Ngày giờ access)",
        "ユーザー区分": "ユーザー区分 (Phân loại người dùng)",
        "ユーザーID": "ユーザーID (user_id)",
        "ユーザー名": "ユーザー名 (Tên người dùng)",
        "画面名": "画面名 (Tên màn hình)",
        "アクセス内容": "アクセス内容 (Nội dung access)",
        "備考": "備考 (note)",
        "登録者ID": "登録者ID (ID người tạo)",
        "登録日時": "登録日時 (Ngày giờ tạo)",
        "更新者ID": "更新者ID (ID người cập nhật)",
        "更新日時": "更新日時 (Ngày giờ cập nhật)",
        "メールアドレス": "メールアドレス (Địa chỉ email)",
        "パスワード": "パスワード (Mật khẩu)",
        "ロール": "ロール (role)",
        "パスワード有効期限": "パスワード有効期限 (Thời hạn mật khẩu)",
        "ログイントークン": "ログイントークン (login token)",
        "ステータス": "ステータス (status)",
        "削除日時": "削除日時 (Ngày giờ xóa)",
        "本文": "本文 (body)",
        "変更確認必須規約": "変更確認必須規約 (Quy định bắt buộc xác nhận thay đổi)",
        "口座審査番号": "口座審査番号 (Số xét duyệt tài khoản)",
        "クリエイター申請ID": "クリエイター申請ID (ID request creator)",
        "金融機関": "金融機関 (Tổ chức tài chính)",
        "支店コード": "支店コード (Mã chi nhánh)",
        "口座の種類": "口座の種類 (Loại tài khoản)",
        "ゆうちょ番号フラグ": "ゆうちょ番号フラグ (flag số bưu điện)",
        "ゆうちょ番号": "ゆうちょ番号 (Số bưu điện)",
        "口座番号": "口座番号 (Số tài khoản)",
        "口座名義": "口座名義 (Tên chủ tài khoản)",
        "NGチェックID": "NGチェックID (ID kiểm tra NG)",
        "業態": "業態 (Loại hình kinh doanh)",
        "金融機関等名称": "金融機関等名称 (Tên tổ chức tài chính)",
        "店舗名称": "店舗名称 (Tên cửa hàng)",
        "金融機関等コード": "金融機関等コード (Mã tổ chức tài chính)",
        "店舗コード": "店舗コード (Mã cửa hàng)",
        "日銀当座勘定取引店": "日銀当座勘定取引店 (Cửa hàng giao dịch tài khoản hiện tại BOJ)",
        "Toユーザー種別": "Toユーザー種別 (Loại người dùng nhận)",
        "Fromユーザー種別": "Fromユーザー種別 (Loại người dùng gửi)",
        "返信用メールアドレス": "返信用メールアドレス (Địa chỉ email trả lời)",
        "件名": "件名 (Tiêu đề)",
        "内容": "内容 (Nội dung)",
        "複合機用ID": "複合機用ID (ID dùng cho máy in đa năng)",
        "クリエイターID": "クリエイターID (ID creator)",
        "商品名": "商品名 (Tên sản phẩm)",
        "複合機印刷用画像URL": "複合機印刷用画像URL (URL hình ảnh in đa năng)",
        "公式サイトサムネイルURL": "公式サイトサムネイルURL (URL hình thu nhỏ trang chính thức)",
        "QR画像URL": "QR画像URL (URL hình ảnh QR)",
        "公開開始日時": "公開開始日時 (Ngày giờ bắt đầu công khai)",
        "公開終了日時": "公開終了日時 (Ngày giờ kết thúc công khai)",
        "NG対象": "NG対象 (Đối tượng NG)",
        "コンテンツ申請ID": "コンテンツ申請ID (ID request nội dung)",
        "コンテンツID": "コンテンツID (ID nội dung)",
        "販売申請ID": "販売申請ID (ID request bán hàng)",
        "印刷設定ID": "印刷設定ID (ID cài đặt in)",
        "停止理由コメント": "停止理由コメント (Bình luận lý do dừng)",
        "停止解除理由コメント": "停止解除理由コメント (Bình luận lý do hủy dừng)",
        "クリエイター識別子": "クリエイター識別子 (Định danh creator)",
        "変更利用規約同意": "変更利用規約同意 (Đồng ý thay đổi điều khoản sử dụng)",
        "最終ログイン日時": "最終ログイン日時 (Ngày giờ đăng nhập cuối cùng)",
        "ログイン試行回数": "ログイン試行回数 (Số lần thử đăng nhập)",
        "ログイン解除日時": "ログイン解除日時 (Ngày giờ mở khóa đăng nhập)",
        "更新試行回数": "更新試行回数 (Số lần thử cập nhật)",
        "更新ロック解除日時": "更新ロック解除日時 (Ngày giờ mở khóa cập nhật)",
        "クリエイター活動申請ID": "クリエイター活動申請ID (ID request hoạt động creator)",
        "クリエイター名": "クリエイター名 (Tên creator)",
        "バナーURL": "バナーURL (URL biểu ngữ)",
        "アイコンURL": "アイコンURL (URL đình chỉ)",
        "携帯電話番号": "携帯電話番号 (Số điện thoại di động)",
        "ワンタイムコード": "ワンタイムコード (Mã một lần)",
        "ワンタイムコード有効期限": "ワンタイムコード有効期限 (Thời hạn mã một lần)",
        "試行回数": "試行回数 (Số lần thử)",
        "トークン": "トークン (Mã thông báo)",
        "トークン有効期限": "トークン有効期限 (Thời hạn mã thông báo)",
        "認証フラグ": "認証フラグ (flag xác thực)",
        "ロック解除日時": "ロック解除日時 (Ngày giờ mở khóa)",
        "生成日時": "生成日時 (Ngày giờ tạo)",
        "氏名": "氏名 (Họ tên)",
        "カナ": "カナ (Kana)",
        "生年月日": "生年月日 (Ngày sinh)",
        "郵便番号": "郵便番号 (Mã bưu điện)",
        "都道府県名": "都道府県名 (Tên tỉnh)",
        "市区町村": "市区町村 (Thành phố/Quận/Huyện)",
        "丁・番地": "丁・番地 (Địa chỉ lô/số nhà)",
        "建物名・部屋番号": "建物名・部屋番号 (Tên tòa nhà/số phòng)",
        "審査番号": "審査番号 (Số xét duyệt)",
        "ログインURL": "ログインURL (URL đăng nhập)",
        "クリエイター本人情報審査ID": "クリエイター本人情報審査ID (ID xét duyệt thông tin cá nhân creator)",
        "電話番号": "電話番号 (Số điện thoại)",
        "アクセス管理者ID": "アクセス管理者ID (ID quản trị viên access)",
        "バージョン": "バージョン (version)",
        "利用規約ID": "利用規約ID (ID điều khoản sử dụng)",
        "該当月": "該当月 (Tháng tương ứng)",
        "支払い予定日": "支払い予定日 (Ngày thanh toán dự kiến)",
        "支払い件数": "支払い件数 (Số lượng thanh toán)",
        "重要通知フラグ": "重要通知フラグ (flag thông báo quan trọng)",
        "重要通知表示フラグ": "重要通知表示フラグ (flag hiển thị thông báo quan trọng)",
        "表示フラグ": "表示フラグ (flag hiển thị)",
        "ソート順": "ソート順 (Thứ tự sort)",
        "表示文言": "表示文言 (text hiển thị)",
        "通知件名": "通知件名 (title thông báo)",
        "通知本文": "通知本文 (body thông báo)",
        "請求管理番号": "請求管理番号 (Số quản lý hóa đơn)",
        "支払い金額(税込)": "支払い金額(税込) (Số tiền thanh toán bao gồm thuế)",
        "支払い金額(税抜)": "支払い金額(税抜) (Số tiền thanh toán không bao gồm thuế)",
        "消費税等": "消費税等 (Thuế tiêu thụ)",
        "源泉徴収税率": "源泉徴収税率 (Tỷ lệ thuế khấu trừ tại nguồn)",
        "源泉徴収税": "源泉徴収税 (Thuế khấu trừ tại nguồn)",
        "対象開始日": "対象開始日 (Ngày bắt đầu áp dụng)",
        "対象終了日": "対象終了日 (Ngày kết thúc áp dụng)",
        "支払日": "支払日 (Ngày thanh toán)",
        "銀行名": "銀行名 (Tên ngân hàng)",
        "支店名": "支店名 (Tên chi nhánh)",
        "印刷設定": "印刷設定 (Cài đặt in)",
        "プリント番号": "プリント番号 (mã print)",
        "単価": "単価 (Đơn giá)",
        "差し戻し": "差し戻し (reject)",
        "数量": "数量 (Số lượng)",
        "小計": "小計 (Tổng phụ)",
        "全国地方公共団体コード": "全国地方公共団体コード (Mã cơ quan chính quyền địa phương toàn quốc)",
        "(旧)郵便番号(5桁)": "(旧)郵便番号(5桁) (Mã bưu điện cũ 5 chữ số)",
        "郵便番号(7桁)": "郵便番号(7桁) (Mã bưu điện 7 chữ số)",
        "都道府件名(カタカナ)": "都道府件名(カタカナ) (Tên tỉnh bằng Kana)",
        "市区町村(カタカナ)": "市区町村(カタカナ) (Tên thành phố/quận/huyện bằng Kana)",
        "町域名(カタカナ)": "町域名(カタカナ) (Tên khu vực bằng Kana)",
        "町域名": "町域名 (Tên khu vực)",
        "一町域が二以上の郵便番号で表されるフラグ": "一町域が二以上の郵便番号で表されるフラグ (flag khu vực được biểu thị bằng hai mã bưu điện trở lên)",
        "小字毎に番地が起番されている町域フラグ": "小字毎に番地が起番されている町域フラグ (flag khu vực có số địa chỉ được đánh số theo từng đơn vị nhỏ)",
        "丁目を有する町域フラグ": "丁目を有する町域フラグ (flag khu vực có lô)",
        "一つの郵便番号で二以上の町域を表すフラグ": "一つの郵便番号で二以上の町域を表すフラグ (flag một mã bưu điện biểu thị hai khu vực trở lên)",
        "更新区分": "更新区分 (Phân loại cập nhật)",
        "変更理由区分": "変更理由区分 (Phân loại lý do thay đổi)",
        "利用日時": "利用日時 (Ngày giờ sử dụng)",
        "コンテンツ名": "コンテンツ名 (Tên nội dung)",
        "カラーモード": "カラーモード (Chế độ màu)",
        "用紙サイズ": "用紙サイズ (Kích thước giấy)",
        "単価(税込)": "単価(税込) (Đơn giá bao gồm thuế)",
        "使用回数": "使用回数 (Số lần sử dụng)",
        "価格": "価格 (Giá)",
        "両面設定": "両面設定 (Cài đặt in hai mặt)",
        "販売情報審査番号": "販売情報審査番号 (Số xét duyệt thông tin bán hàng)",
        "申請日": "申請日 (Ngày request)",
        "アクセスユーザー": "アクセスユーザー (Người dùng access)",
        "解約申請番号": "解約申請番号 (Số request hủy hợp đồng)",
        "T番号": "T番号 (Số T)",
        "事業者名": "事業者名 (Tên doanh nghiệp)",
        "事業登記住所": "事業登記住所 (Địa chỉ đăng ký kinh doanh)",
        "T番号審査ID": "T番号審査ID (ID xét duyệt số T)",
        "通知区分": "通知区分 (Phân loại thông báo)",
        "NG通知対象": "NG通知対象 (Đối tượng thông báo NG)",
        "申請ID": "申請ID (ID request)",
        "論理エンティティ名": "論理エンティティ名 (Tên logic Entity)",
        "物理エンティティ名": "物理エンティティ名 (Tên vật lý Entity)",
        "タグ": "タグ (thẻ)",
        # ĐN code
        "1:DNP管理者": "1:DNP管理者/1: Người quản lý DNP",
        "2: DNP担当者": "2: DNP担当者/2: Người phụ trách DNP",
        "3: FM担当者（個人情報参照あり）": "3: FM担当者（個人情報参照あり）/3: Người phụ trách FM (có quyền truy cập thông tin cá nhân)",
        "4: FM担当者（個人情報参照なし）": "4: FM担当者（個人情報参照なし）/4: Người phụ trách FM (không có quyền truy cập thông tin cá nhân)",
        "5: FMシステム担当者": "5: FMシステム担当者/5: Người phụ trách hệ thống FM",
        "1：サービス利用規約": "1：サービス利用規約/1: Điều khoản sử dụng dịch vụ",
        "2：ガイドライン": "2：ガイドライン/2: Hướng dẫn",
        "3：プライバシーポリシー": "3：プライバシーポリシー/3: Chính sách bảo mật",
        "＞＞追加される可能性あり": "Có thể được bổ sung",
        "1：普通預金": "1：普通預金/1: Tài khoản tiết kiệm thông thường",
        "2：定期預金": "2：定期預金/2: Tài khoản tiết kiệm có kỳ hạn",
        "3：総合口座": "3：総合口座/3: Tài khoản tổng hợp",
        "4：積立定期預金": "4：積立定期預金/4: Tài khoản tích lũy định kỳ",
        "1:口座の記号・番号を入力": "1:口座の記号・番号を入力/1: Nhập ký hiệu và số tài khoản",
        "2:店番・口座番号を入力": "2:店番・口座番号を入力/2: Nhập mã chi nhánh và số tài khoản",
        "1：審査用CSV未出力": "1：審査用CSV未出力/1: Chưa export CSV để xét duyệt",
        "2：審査用CSV出力済み": "2：審査用CSV出力済み/2: Đã export CSV để xét duyệt",
        "3：審査OK": "3：審査OK/3: Xét duyệt OK",
        "4：審査NG": "4：審査NG/4: Xét duyệt NG",
        "1：下書き": "1：下書き/1: Bản nháp",
        "2：販売承認済み": "2：販売承認済み/2: Đã approve để bán",
        "3 :プリント番号採番済み": "3 :プリント番号採番済み/3: Đã cấp số in",
        "4：取り下げ": "4：取り下げ/4: thu hồi",
        "5：停止": "5：停止/5: đình chỉ",
        "6：FM下書き": "6：FM下書き/6: Bản nháp FM",
        "1：申請中": "1：申請中/1: Đang request",
        "2：承認済み": "2：承認済み/2: Đã approve",
        "3：取り下げ": "3：取り下げ/3: Đã rút lại",
        "01：初回登録完了": "01：初回登録完了/01: Hoàn tất đăng ký lần đầu",
        "02：本人確認情報下書き": "02：本人確認情報下書き/02: Bản nháp thông tin xác minh danh tính",
        "03：本人確認申請中": "03：本人確認申請中/03: Đang request xác minh danh tính",
        "04：本人確認審査完了": "04：本人確認審査完了/04: Đã hoàn tất xét duyệt xác minh danh tính",
        "05：初回口座審査中": "05：初回口座審査中/05: Đang xét duyệt tài khoản lần đầu",
        "06：活動中　": "06：活動中　/06: Đang hoạt động",
        "07：活動中（口座NG）": "07：活動中（口座NG）/07: Đang hoạt động (tài khoản NG)",
        "08：活動中（クリエイタープロフィール未申請）": "08：活動中（クリエイタープロフィール未申請）/08: Đang hoạt động (chưa request profile creator)",
        "09：活動中（クリエイタープロフィール申請中）": "09：活動中（クリエイタープロフィール申請中）/09: Đang hoạt động (đang request profile creator)",
        "10：退会": "10：退会/10: thoát hội",
        "11：停止（ログイン可）": "11：停止（ログイン可）/11: đình chỉ (vẫn đăng nhập được)",
        "11：停止（ログイン不可）": "11：停止（ログイン不可）/11: đình chỉ (không thể đăng nhập)",
        "12：その他NG": "12：その他NG/12: Lý do NG khác",
        "1：クリエイター名": "1：クリエイター名/1: Tên Creator",
        "2：クリエイターバナー": "2：クリエイターバナー/2: Banner của Creator",
        "3：クリエイターアイコン": "3：クリエイターアイコン/3: đình chỉ của Creator",
        "1：審査中": "1：審査中/1: Đang xét duyệt",
        "2：審査OK": "2：審査OK/2: Xét duyệt OK",
        "3：審査NG": "3：審査NG/3: Xét duyệt NG",
        "1：本人確認審査": "1：本人確認審査/1: Xét duyệt xác minh danh tính",
        "2：口座審査": "2：口座審査/2: Xét duyệt tài khoản",
        "3：コンテンツ審査": "3：コンテンツ審査/3: Xét duyệt content",
        "4：クリエイタープロフィール審査": "4：クリエイタープロフィール審査/4: Xét duyệt hồ sơ Creator",
        "5:解約": "5:解約/5: Hủy dịch vụ",
        "1.審査中": "1.審査中/1: Đang xét duyệt",
        "2.審査OK": "2.審査OK/2: Xét duyệt OK",
        "3.審査NG": "3.審査NG/3: Xét duyệt NG",
        "4.他審査OK": "4.他審査OK/4: Xét duyệt khác OK",
        "5.他審査NG": "5.他審査NG/5: Xét duyệt khác NG",
        "1：未同意": "1：未同意/1: Chưa đồng ý",
        "2：同意済み": "2：同意済み/2: Đã đồng ý",
        "1：未振込": "1：未振込/1: Chưa chuyển khoản",
        "2：振込済み": "2：振込済み/2: Đã chuyển khoản",
        "3：振込NG": "3：振込NG/3: Chuyển khoản thất bại",
        "1：支払い明細未作成": "1：支払い明細未作成/1: Chưa tạo bảng chi tiết thanh toán",
        "2：支払い明細作成済": "2：支払い明細作成済/2: Đã tạo bảng chi tiết thanh toán",
        "3：振り込み済み": "3：振り込み済み/3: Đã chuyển khoản",
        "4：振込NG": "4：振込NG/4: Chuyển khoản thất bại",
        "5：繰り越し": "5：繰り越し/5: Chuyển sang kỳ sau",
        "1：振込データ未作成": "1：振込データ未作成/1: Chưa tạo dữ liệu chuyển khoản",
        "2：振り込みデータ作成済み": "2：振り込みデータ作成済み/2: Đã tạo dữ liệu chuyển khoản",
        "3：振込結果取り込み済み": "3：振込結果取り込み済み/3: Đã nhập kết quả chuyển khoản",
        "01：普通紙 B5": "01：普通紙 B5/01: Giấy thường khổ B5",
        "02：普通紙 A4": "02：普通紙 A4/02: Giấy thường khổ A4",
        "03：普通紙 B4": "03：普通紙 B4/03: Giấy thường khổ B4",
        "04：普通紙 A3": "04：普通紙 A3/04: Giấy thường khổ A3",
        "05：はがき": "05：はがき/05: Bưu thiếp",
        "06：A4 光沢紙": "06：A4 光沢紙/06: Giấy bóng khổ A4",
        "07：ブロマイド L判": "07：ブロマイド L判/07: Ảnh in L-size",
        "08：ブロマイド 2L判": "08：ブロマイド 2L判/08: Ảnh in 2L-size",
        "12：ブロマイド スクエア": "12：ブロマイド スクエア/12: Ảnh in vuông",
        "13：シール紙L 判": "13：シール紙L 判/13: Giấy dán L-size",
        "14：シール紙2L 判": "14：シール紙2L 判/14: Giấy dán 2L-size",
        "15：シール紙スクエア": "15：シール紙スクエア/15: Giấy dán vuông",
        "1：白黒": "1：白黒/1: Đen trắng",
        "2：カラー": "2：カラー/2: Màu",
        "1：片面": "1：片面/1: Một mặt",
        "2：両面横綴じ": "2：両面横綴じ/2: Hai mặt - gáy ngang",
        "3：両面縦綴じ": "3：両面縦綴じ/3: Hai mặt - gáy dọc",
        "1：停止": "1：停止/1: đình chỉ",
        "2：差し戻し": "2：差し戻し/2: reject",
        "1：販売画像": "1：販売画像/1: ảnh bán",
        "2：クリエイター活動": "2：クリエイター活動/2: Hoạt động của creator",
        "01：反社": "01：反社/01: Liên quan đến tổ chức phản xã hội",
        "02：適格請求書発行事業者情報": "02：適格請求書発行事業者情報/02: Thông tin doanh nghiệp phát hành hóa đơn hợp lệ",
        "03：クリエイター名": "03：クリエイター名/03: Tên creator",
        "04：クリエイターバナー": "04：クリエイターバナー/04: Banner của creator",
        "05：クリエイターアイコン": "05：クリエイターアイコン/05: đình chỉ của creator",
        "06：販売画像": "06：販売画像/06: ảnh bán",
        "07：アカウント停止理由": "07：アカウント停止理由/07: Lý do đình chỉ account",
        "08：販売画像停止理由": "08：販売画像停止理由/08: Lý do đình chỉ ảnh bán hàng",
        # list status không có số
        "論理カラム名": "Tên column logic",
        "１と重複のため不要": "Vì trùng với 1 nên không cần",
        "マスターデータ": "data master",
        "物理カラム名": "Tên column vật lý",
        "ステータス概要": "overview status",
        "ステータス変更概要": "overview thay đổi status",
        "物理エンティティ名": "Tên vật lý Entity",
        "論理エンティティ名": "Tên logic Entity",
        "支払い保留": "支払い保留\nbảo lưu thanh toán",
        "通常計算": "通常計算\ntính toán thường",
        "期末計算": "期末計算\ntính toán cuối kỳ",
        "期末失効計算": "期末失効計算\nTính toán mất hiệu lực vào cuối kỳ",
        "ロイヤリティ繰越": "ロイヤリティ繰越\nChuyển tiếp tiền bản quyền",
        "退会計算": "退会計算\nTính toán cho người dùng đã thoát hội",
        "退会執行計算": "退会執行計算\nTính toán cho người dùng đã thoát hội",
        "口座NG退会執行計算": "口座NG退会執行計算\nTính toán thoát hội khi tài khoản ngân hàng NG",
        "下書き": "下書き\nBản nháp",
        "販売承認済み": "販売承認済み\nĐã approve để bán",
        "プリント番号採番済み": "プリント番号採番済み\nĐã cấp số in",
        "取り下げ": "取り下げ\nthu hồi",
        "停止": "停止\nđình chỉ",
        "FM下書き": "FM下書き\nBản nháp FM",
        "申請中": "申請中\nĐang request",
        "承認済み": "承認済み\nĐã được approve",
        "初回登録完了": "初回登録完了\nHoàn tất đăng ký lần đầu",
        "本人確認情報下書き": "本人確認情報下書き\nBản nháp thông tin xác minh danh tính",
        "本人確認申請中": "本人確認申請中\nĐang request xác minh danh tính",
        "本人確認審査完了": "本人確認審査完了\nĐã hoàn tất xét duyệt xác minh danh tính",
        "初回口座審査中": "初回口座審査中\nĐang xét duyệt tài khoản lần đầu",
        "活動中　": "活動中　\nĐang hoạt động",
        "活動中　（口座NG）": "活動中　（口座NG）\nĐang hoạt động (tài khoản NG)",
        "活動中（クリエイタープロフィール未申請）": "活動中（クリエイタープロフィール未申請）\nĐang hoạt động (chưa request profile creator)",
        "活動中（クリエイタープロフィール申請中）": "活動中（クリエイタープロフィール申請中）\nĐang hoạt động (đang chờ request profile creator)",
        "退会": "退会\nthoát hội",
        "停止（ログイン可）": "停止（ログイン可）\nđình chỉ (vẫn đăng nhập được)",
        "停止（ログイン不可）": "停止（ログイン不可）\nđình chỉ (không thể đăng nhập)",
        "その他NG": "その他NG\nLý do NG khác",
        "審査中": "審査中\nĐang xét duyệt",
        "審査OK": "審査OK\nXét duyệt OK",
        "審査NG": "審査NG\nXét duyệt NG",
        "本人確認審査": "本人確認審査\nXét duyệt xác minh danh tính",
        "口座審査": "口座審査\nXét duyệt tài khoản",
        "コンテンツ審査": "コンテンツ審査\nXét duyệt content",
        "クリエイタープロフィール審査": "クリエイタープロフィール審査\nXét duyệt hồ sơ Creator",
        "解約": "解約\nHủy dịch vụ",
        "他審査OK": "他審査OK\nXét duyệt khác OK",
        "他審査NG": "他審査NG\nXét duyệt khác NG",
        "未同意": "未同意\nChưa đồng ý",
        "同意済み": "同意済み\nĐã đồng ý",
        "未振込": "未振込\nChưa chuyển khoản",
        "振込済み": "振込済み\nĐã chuyển khoản",
        "振込NG": "振込NG\nChuyển khoản thất bại",
        "支払い明細未作成": "支払い明細未作成\nChưa tạo bảng chi tiết thanh toán",
        "支払い明細作成済": "支払い明細作成済\nĐã tạo bảng chi tiết thanh toán",
        "繰り越し": "繰り越し\nChuyển sang kỳ sau",
        "振込データ未作成": "振込データ未作成\nChưa tạo dữ liệu chuyển khoản",
        "振り込みデータ作成済み": "振り込みデータ作成済み\nĐã tạo dữ liệu chuyển khoản",
        "振込結果取り込み済み": "振込結果取り込み済み\nĐã nhập kết quả chuyển khoản",
        "普通紙 B5": "普通紙 B5\nGiấy thường khổ B5",
        "普通紙 A4": "普通紙 A4\nGiấy thường khổ A4",
        "普通紙 B4": "普通紙 B4\nGiấy thường khổ B4",
        "普通紙 A3": "普通紙 A3\nGiấy thường khổ A3",
        "はがき": "はがき\nBưu thiếp",
        "A4 光沢紙": "A4 光沢紙\nGiấy bóng khổ A4",
        "ブロマイド L判": "ブロマイド L判\nẢnh in L-size",
        "ブロマイド 2L判": "ブロマイド 2L判\nẢnh in 2L-size",
        "ブロマイド スクエア": "ブロマイド スクエア\nẢnh in vuông",
        "シール紙L 判": "シール紙L 判\nGiấy dán L-size",
        "シール紙2L 判": "シール紙2L 判\nGiấy dán 2L-size",
        "シール紙スクエア": "シール紙スクエア\nGiấy dán vuông",
        "白黒": "白黒\nĐen trắng",
        "カラー": "カラー\nMàu",
        "片面": "片面\nMột mặt",
        "両面横綴じ": "両面横綴じ\nHai mặt - gáy ngang",
        "両面縦綴じ": "両面縦綴じ\nHai mặt - gáy dọc",
        "差し戻し": "差し戻し\nreject",
        "販売画像": "販売画像\nảnh bán",
        "クリエイター活動": "クリエイター活動\nHoạt động của creator",
        "反社": "反社\nLiên quan đến tổ chức phản xã hội",
        "適格請求書発行事業者情報": "適格請求書発行事業者情報\nThông tin doanh nghiệp phát hành hóa đơn hợp lệ",
        "クリエイター名": "クリエイター名\nTên creator",
        "クリエイターバナー": "クリエイターバナー\nBanner của creator",
        "クリエイターアイコン": "クリエイターアイコン\nicon của creator",
        "アカウント停止理由": "アカウント停止理由\nLý do đình chỉ account",
        "販売画像停止理由": "販売画像停止理由\nLý do đình chỉ ảnh bán hàng",
        "FMDNP管理よりコンテンツ登録時に下書きボタン押下時に登録した場合": "Khi đăng ký nội dung từ quản lý FMDNP và nhấn nút 'Bản nháp' thì gán trạng thái này.",
        "FMDNPにて承認された際にプリント番号が採番を行った場合に付与するステータス": "Khi số in được cấp sau khi được phê duyệt từ FMDNP thì gán trạng thái này.",
        "クリエイターにより取り下げされた際に付与するステータス": "Khi creator rút lại yêu cầu thì gán trạng thái này.",
        "FMDNPにて販売停止処理が行われた際に付与するステータス": "Khi xử lý dừng bán được thực hiện từ FMDNP thì gán trạng thái này.",
        "クリエイターがクリエイタープロフィールか販売画像の申請があった際に承認済み、もしくは取り下げのレコードしかなかった場合にレコードを新規で作成しこのステータスを付与する。": "Khi creator nộp hồ sơ creator hoặc ảnh bán, nhưng chỉ có bản ghi đã được phê duyệt hoặc đã rút lại, thì tạo bản ghi mới và gán trạng thái này.",
        "FMDNPにて承認された際に付与するテーブル": "Khi được FMDNP phê duyệt thì gán trạng thái này.",
        "クリエイターにより販売作品の申請が取り下げされた際に他に紐づいている申請がない場合に付与するステータス": "Khi creator rút lại yêu cầu bán tác phẩm và không còn yêu cầu liên kết nào khác thì gán trạng thái này.",
        "クリエイターが初回にメールアドレスと携帯番号と登録しクリエイターマスタに新規でレコードを追加した際に付与するステータス": "Khi creator lần đầu đăng ký email và số điện thoại và tạo bản ghi mới trong master creator thì gán trạng thái này.",
        "本人確認審査入力時に下書きボタン押下で登録処理を行った際に付与するステータス": "Khi nhập thông tin xác minh danh tính và nhấn nút 'Bản nháp' thì gán trạng thái này.",
        "YSD審査連携ボタン押下時に付与するステータス": "Khi nhấn nút liên kết xét duyệt YSD thì gán trạng thái này.",
        "YSD審査結果がOKだった際に付与するステータス": "Khi kết quả xét duyệt YSD là OK thì gán trạng thái này.",
        "DNP審査にて反社OKだった場合に付与されるステータス": "Khi kiểm tra phản xã hội trong xét duyệt DNP là OK thì gán trạng thái này.",
        "クリエイタープロフィールの初回承認が全て完了した際に付与されるステータス": "Khi toàn bộ các bước phê duyệt hồ sơ creator đầu tiên hoàn tất thì gán trạng thái này.",
        "口座審査がOKだった際に付与されるステータス": "Khi xét duyệt tài khoản là OK thì gán trạng thái này.",
        "8:活動中（クリエイタープロフィール未申請）の状態からクリエイタープロフィールの初回申請が行われた際に付与するステータス": "Khi đang ở trạng thái 'Đang hoạt động (chưa đăng ký hồ sơ creator)' mà hồ sơ creator được đăng ký lần đầu thì gán trạng thái này.",
        "退会が承認された際に付与するステータス": "Khi yêu cầu rút khỏi hệ thống được phê duyệt thì gán trạng thái này.",
        "FMDNPにより停止（ログイン可）が選択され登録された際に付与するステータス": "Khi trạng thái 'Đình chỉ (đăng nhập được)' được chọn và đăng ký từ FMDNP thì gán trạng thái này.",
        "FMDNPにより停止（ログイン不可）が選択され登録された際に付与するステータス": "Khi trạng thái 'Đình chỉ (không thể đăng nhập)' được chọn và đăng ký từ FMDNP thì gán trạng thái này.",
        "反社チェックでNGだった場合に付与するステータス": "Khi kết quả kiểm tra phản xã hội là NG thì gán trạng thái này.",
        "クリエイターより申請があった場合に付与するステータス": "Khi có yêu cầu từ creator thì gán trạng thái này.",
        "FMDNPによりクリエイタープロフィール領域にて審査OKだった場合に付与するステータス": "Khi kết quả xét duyệt hồ sơ creator trong FMDNP là OK thì gán trạng thái này.",
        "FMDNPによりクリエイタープロフィール領域にて審査NGだった場合に付与するステータス": "Khi kết quả xét duyệt hồ sơ creator trong FMDNP là NG thì gán trạng thái này.",
        "口座審査が完了した時に付与するステータス": "Khi hoàn tất xét duyệt tài khoản thì gán trạng thái này.",
        "振り込み実施時に口座NGにて振り込みNGになった際に付与するステータス": "Khi chuyển khoản thực hiện nhưng bị NG do tài khoản NG thì gán trạng thái này.",
        "承認されたなど正常系の通知であった際に付与するステータス": "Khi có thông báo hợp lệ như phê duyệt thì gán trạng thái này.",
        "差し戻しなど異常系の通知であった際に付与するステータス": "Khi có thông báo lỗi như bị trả về thì gán trạng thái này.",
        "本人確認審査の結果通知の際に付与する": "Gán trạng thái này khi có thông báo kết quả xét duyệt xác minh danh tính.",
        "口座審査の結果通知の際に付与する": "Gán trạng thái này khi có thông báo kết quả xét duyệt tài khoản.",
        "コンテンツ審査の結果通知の際に付与する": "Gán trạng thái này khi có thông báo kết quả xét duyệt nội dung.",
        "クリエイタープロフィール審査の結果通知の際に付与する": "Gán trạng thái này khi có thông báo kết quả xét duyệt hồ sơ creator.",
        "解約承認時の結果通知の際に付与する": "Gán trạng thái này khi có thông báo kết quả phê duyệt yêu cầu hủy dịch vụ.",
        "当該の顧客ユニークIDに対して審査がOKだった際に付与するステータス": "Gán trạng thái này khi xét duyệt OK với ID khách hàng tương ứng.",
        "当該の顧客ユニークIDに対して審査がNGだった際に付与するステータス": "Gán trạng thái này khi xét duyệt NG với ID khách hàng tương ứng.",
        "当該のクリエイターにて対して他に審査にて審査がOKだった場合に当該の顧客ユニークIDに対して付与するステータス": "Gán trạng thái này với ID khách hàng tương ứng nếu creator đã từng có một xét duyệt khác là OK.",
        "当該のクリエイターにて対して他に審査にて審査がNGだった場合に当該の顧客ユニークIDに対して付与するステータス": "Gán trạng thái này với ID khách hàng tương ứng nếu creator đã từng có một xét duyệt khác là NG.",
        "更新された利用規約に対して付与するステータス": "Gán trạng thái này khi có bản cập nhật điều khoản sử dụng.",
        "対象の利用規約に同意した際に付与するステータス": "Gán trạng thái này khi đã đồng ý với điều khoản sử dụng.",
        "登録するデータの対象が停止だった際に付与するステータス": "Gán trạng thái này khi dữ liệu được đăng ký có trạng thái là đã dừng.",
        "登録するデータの対象が差し戻しだった際に付与するステータス": "Gán trạng thái này khi dữ liệu được đăng ký bị trả về.",
        "登録するデータの対象が販売画像だった際に付与するステータス": "Gán trạng thái này khi dữ liệu được đăng ký là hình ảnh để bán.",
        "登録するデータの対象がクリエイタープロフィールだった際に付与するステータス": "Gán trạng thái này khi dữ liệu được đăng ký là hồ sơ creator.",
        "クリエイターが申請を行った際に販売申請のデータに申請中がなかった場合に付与して作成する。": "Gán và tạo trạng thái này nếu khi creator gửi đơn mà không có đơn bán nào đang chờ xử lý.",
        "DNP側で申請を行った際に付与するステータス": "Gán trạng thái này khi yêu cầu được thực hiện từ phía DNP.",
        "クリエイターにより申請が取り下げられた場合最後の１つの申請であったら付与するステータス": "Gán trạng thái này nếu creator rút đơn và đó là đơn cuối cùng.",
        "支払い計算実施時に支払い明細書を作成する支払いであった際に付与するステータス": "Gán trạng thái này khi tạo bảng sao kê thanh toán trong quá trình tính toán thanh toán.",
        "支払い明細作成バッチ実行時に正常終了した際に付与するステータス": "Gán trạng thái này khi lô tạo bảng sao kê hoàn tất thành công.",
        "振り込み結果が正常に完了していた際に付与するステータス": "Gán trạng thái này khi chuyển khoản hoàn tất thành công.",
        "振り込み結果が異常で終了していた際に付与するステータス": "Gán trạng thái này khi kết quả chuyển khoản kết thúc với lỗi.",
        "支払い明細計算の際にロイヤリティ繰越で計算された際に付与するステータス": "Gán trạng thái này khi tiền bản quyền được tính toán và chuyển sang kỳ sau.",
        "精算明細データ登録時に付与するステータス": "Gán trạng thái này khi đăng ký dữ liệu sao kê thanh toán.",
        "支払い計算実施時に支払い対象であったが支払い金額が0円を下回った支払いに対して付与するステータス": "Gán trạng thái này khi đối tượng được tính thanh toán nhưng số tiền dưới 0 yên.",
        "支払い明細作成時に手数料を追加した対象となった支払いに対して付与するステータス": "Gán trạng thái này khi thêm phí xử lý vào bảng sao kê.",
        "期末対象月ではない月での精算を行った支払いに対して計算をした場合に付与するステータス": "Gán trạng thái này khi tính toán trong tháng không phải là tháng cuối kỳ.",
        "期末対象月での精算を行った支払いに対して計算をした場合に付与するステータス": "Gán trạng thái này khi tính toán trong tháng cuối kỳ.",
        "期末対象月での精算を行った際に0円を下回った支払いに対して計算をした場合に付与するステータス": "Gán trạng thái này khi trong tháng cuối kỳ, số tiền tính toán dưới 0 yên.",
        "期末対象月ではない月での精算を行った際にロイヤリティが1000円に満たない支払いに対して計算をした場合に付与するステータス": "Gán trạng thái này khi thanh toán ngoài tháng cuối kỳ và tiền bản quyền dưới 1000 yên.",
        "退会ユーザーに対して最終支払いを行った際に付与するステータス": "Gán trạng thái này khi thực hiện khoản thanh toán cuối cho người dùng đã rút lui.",
        "退会ユーザーに対して最終支払いを行ったが支払いが0円に満たないため執行する計算を行った際に付与するステータス": "Gán trạng thái này khi thanh toán cuối cùng dưới 0 yên cho người dùng đã rút lui.",
        "退会ユーザーに対して計算を行う際に口座不備の状態のままだった場合、この計算を行い付与するステータス": "Gán trạng thái này nếu tài khoản bị lỗi khi tính toán thanh toán cho người dùng đã rút lui.",
        "振り込みデータダウンロードをまだ実施していない場合に付与するステータス": "Gán trạng thái này khi dữ liệu chuyển khoản chưa được tải xuống.",
        "振り込みデータダウンロードを実施した際に付与するステータス": "Gán trạng thái này khi đã tải dữ liệu chuyển khoản.",
        "振り込み結果と取り込んだ際に付与するステータス": "Gán trạng thái này khi kết quả chuyển khoản được nhập vào hệ thống.",
        "期末対象月ではない月での精算を行った支払いに対して計算をした場合に付与する付与するステータス": "Gán trạng thái này khi tính toán thanh toán ngoài tháng cuối kỳ.",
        "期末対象月での精算を行った支払いに対して計算をした場合に付与する付与するステータス": "Gán trạng thái này khi tính toán thanh toán trong tháng cuối kỳ.",
        "期末対象月での精算を行った際に0円を下回った支払いに対して計算をした場合に付与する付与するステータス": "Gán trạng thái này khi thanh toán trong tháng cuối kỳ và số tiền dưới 0 yên.",
        "精算明細登録済み": "精算明細登録済み\nĐã đăng ký bảng chi tiết quyết toán.",
        "支払い明細作成済み0円処理": "支払い明細作成済み0円処理\nĐã xử lý tạo bảng sao kê thanh toán có giá trị 0 yên.",
        "同時支払い処理対象": "同時支払い処理対象\nĐối tượng xử lý thanh toán đồng thời.",
        "初期値のステータス": "Trạng thái mặc định ban đầu.",
        "承認済みだと全部承認になるからここは対応済みとかにした方がよいかも？？": "Vì đã được phê duyệt thì toàn bộ sẽ là 'đã phê duyệt', nên có thể nên để là 'đã xử lý'.",
        "このテーブルには何かしらの申請が紐づく必要があるが、取り下げられた場合にレコードを不要にする必要があるため取り下げと業務と合わせて設定してます。": "Bảng này cần liên kết với một yêu cầu nào đó, nếu bị rút lại thì cần xóa bản ghi tương ứng nên trạng thái được cài đặt cùng với quy trình rút đơn.",
        "印刷設定の用紙サイズ": "Cỡ giấy trong thiết lập in.",
        "この処理はバッチになる可能性もあるため、現状未決定": "Vì xử lý này có thể là batch nên hiện tại chưa xác định.",
        "このテーブルの初期ステータスはこのステータス": "Trạng thái mặc định ban đầu của bảng này là trạng thái này.",
        "プリント番号と販売開始日を採番せずに採番待機状態のステータス": "Trạng thái chờ cấp số in và ngày bắt đầu bán mà chưa được cấp.",
        "印刷設定のカラーモード": "Chế độ màu trong cài đặt in",
        "このテーブル自体いらないかも、、、　www": "Có lẽ bản thân bảng này cũng không cần thiết...",
        "通常処理、期末処理で計算された際に手数料などのマイナスになってしまった支払いに付与される": "Gán trạng thái này cho các khoản thanh toán trở thành số âm do phí trong quá trình xử lý thông thường hoặc xử lý cuối kỳ.",
        "振り込みデータ作成に含める対処とするためのステータス": "Trạng thái này được sử dụng để xử lý bao gồm trong việc tạo dữ liệu chuyển khoản.",
        "通常処理、期末処理で計算された際に付与される": "Trạng thái được gán khi việc tính toán được thực hiện trong xử lý thông thường hoặc cuối kỳ.",
        "S3に格納されていることが終了条件": "Điều kiện kết thúc là phải được lưu trữ trên S3.",
        "他に審査IDがある場合は他審査OKにフラグ変更": "Nếu có ID xét duyệt khác, thì chuyển cờ sang trạng thái 'Xét duyệt khác OK'.",
        "他に審査IDがある場合は他審査NGにフラグ変更": "Nếu có ID xét duyệt khác, thì chuyển cờ sang trạng thái 'Xét duyệt khác NG'.",
        "動的に付与　審査取り込み時に除外する": "Gán trạng thái một cách động, loại trừ khi nhập kết quả xét duyệt.",
        "NGだった場合は赤字で表示し未読であった場合は！アイコンを配置する": "Nếu kết quả là NG thì hiển thị bằng màu đỏ, nếu chưa đọc thì hiển thị biểu tượng '!'",
        "クリエイター名、アイコン、バナー全それぞれで管理する": "Tên, biểu tượng và banner của creator được quản lý riêng biệt.",
        "支払い明細作成時の口座が有効か無効化はこのカラムを参照して判定する": "Việc tài khoản có hợp lệ hay không khi tạo bảng chi tiết thanh toán sẽ được xác định dựa vào cột này.",
        "クリエイター名、アイコン、バナー全て揃う必要がある": "Cần có đầy đủ tên, biểu tượng và banner của creator.",
        "口座NGと退会などの状態を同時に管理する必要があり、クリエイターマスタではステータス管理が多くなってしまったのでクリエイター口座マスタにて管理するように決定": "Do cần quản lý đồng thời trạng thái như tài khoản NG và rút lui, nên việc quản lý trạng thái trở nên phức tạp ở master creator, đã quyết định chuyển sang quản lý ở master tài khoản creator.",
        "YSD審査中の際はこのステータスとなる": "Khi đang trong quá trình xét duyệt YSD thì gán trạng thái này.",
        "DNPの審査対象となるクリエイターもこのステータス": "Creator thuộc diện xét duyệt của DNP cũng được gán trạng thái này."
}