translate_list = {
   # codding design
        # codding design
        "- API Create/ update thì validate maxlength = maxlength database": "APIのCreate/Updateではmaxlength = DBのmaxlengthをバリデーションする",
        "- API Search thì không cần validate nếu đây là tham số trong điều kiện search": "APIのSearchでは検索条件のパラメータであればバリデーション不要",
        "- Validate Start Date < EndDate": "Start Date < EndDateのバリデーション",
        "- Validate String nhập vào theo kiểu dữ liệu date format.": "日付形式のデータ型に従って入力文字列をバリデーションする",
        "- Validate bắt buộc nhập 1 trường nếu trường còn lại bằng giá trị": "ある項目が指定された値の場合、他の1項目の入力が必須となるバリデーション",
        "- Validate bắt buộc nhập giá trị": "値の入力必須バリデーション",
        "- Validate giá trị chỉ bao gồm số half size": "値は半角数字のみを含むバリデーション",
        "- Validate giá trị nhập là timstamps format": "入力値がタイムスタンプ形式であることをバリデーション",
        "- Validate giá trị nhập phải thuộc danh sách Enum được khai báo": "入力値が定義済みのEnumリストに含まれることをバリデーション",
        "- Validate kiểu số Integer để khi convert bằng mapper không bị lỗi.": "マッパーで変換時にエラーとならないよう、整数型をバリデーションする",
        "- Validate list email": "メールアドレスのリストをバリデーションする",
        "- Validate mã bưu điện": "郵便番号をバリデーションする",
        "I) Mục đích/ Ý nghĩa:": "I）目的／意味：",
        "II) Các step:": "II）ステップ：",
        "STT": "No",
        "Step": "ステップ",
        "Liên hệ với leader để đi copy code ở dự án khác": "他の案件を参照する",
        "1) Convert Từ Request thành Form": "1) リクエストからフォームに変換する",
        "- Validate nhóm các trường phải có ít nhất 1 trường có giá trị là": "フィールドグループ内で少なくとも1つのフィールドに値が存在することをバリデーション",
        "- Validate số From < số To": "数値From < 数値Toのバリデーション",
        "- Validate số điện thoại hoặc số Fax": "電話番号またはFax番号のバリデーション",
        "- Validate định dạng email": "メール形式のバリデーション",
        "1) Các thành phần cơ bản của chức năng": "1）機能の基本構成要素",
        "1) Try {} catch và set stateException": "1）Try {} catchでstateExceptionを設定する",
        "2) Các function dùng chung": "2）共通関数",
        "2) Khai báo protobuf": "2）protobufの定義",
        "2) Log Begin method + end method.": "2）メソッドの開始と終了のログ出力",
        "3) Các Enum, Constants …": "3）Enum、定数など",
        "4) Các QA liên quan": "4）関連するQA",
        "5) Các Bugs liên quan": "5）関連するバグ",
        "6) Các action cần insert thêm vào access Log": "6）accessログに追加すべきアクション",
        "6) Xác thực mật khẩu\n - Trường hợp mật khẩu đúng, đi tiếp bước 4\n - Trường hợp sai mật khẩu, update login_attempt + 1, nếu login_attempt >= 5, update unlock_at = thời gian hiện tại + 15p": "6）パスワード認証\n - パスワードが正しければステップ4へ進む\n - 間違っていればlogin_attemptを+1。login_attempt >= 5の場合、unlock_atを現在時刻＋15分に更新",
        "7) Kiểm tra ngày hết hạn mật khẩu\n7.1 Nếu ngày hết hạn mật khẩu nhỏ hơn ngày hiện tại thì trả về lỗi. Response sẽ có state vả message dạng\n     + Ghi log warning:パスワードの有効期限が切れています。\n     + Trả về response có status(trong state) là 901\n7.2.Nếu ngày hết hạn mật khẩu lớn hơn ngày hiện tại thì xử lý tiếp mục 8": "7）パスワード有効期限の確認\n7.1 有効期限が現在日時より過ぎている場合、エラーを返す。レスポンスには以下を含む：\n     + ログ警告: パスワードの有効期限が切れています。\n     + stateにstatus 901を返す\n7.2 有効期限が現在日時より後であれば、ステップ8へ進む",
        "8) Update lại các column trong table creator\n - update_at, last_login_at, unlock_at: update về ngày hiện tại\n - login_attempt về 0\n - login_token = loginToken từ UUID": "8）creatorテーブルのカラムを更新\n - update_at、last_login_at、unlock_atを現在日時に更新\n - login_attemptを0にリセット\n - login_tokenにUUIDからのloginTokenを設定",
        "9) Tạo response trả về": "9）レスポンスを生成して返す",
        "Boolean": "ブール型",
        "Bảng lưu thông tin mã auth code khi login của creator": "creatorのログイン時の認証コード情報を保持するテーブル",
        "Bảng lưu thông tin đăng nhập của creator": "creatorのログイン情報を保持するテーブル",
        "Bắt buộc": "require",
        "creator.status = 10：退会 và ngày hiện tại <= ngày cuối tháng 2 năm sau": "creator.status = 10：退会　かつ現在日付　<=　翌年の2月末日",
        "Không được phép": "許可されない",
        "Được phép": "許可される",
        "chưa đồng ý điều khoản sử dụng": "利用契約に未同意",
        "creator.status được phép thực hiện": "許可されるcreator.status",
        "Chú ý": "注意",
        "Chỉ cần mô tả các nested class": "ネストされたクラスのみ記述すればよい",
        "Cấu trúc Form": "フォーム構造",
        "Danh sách các trường áp dụng": "適用されるフィールドの一覧",
        "II) Các step:\n1) Convert Từ Request thành Form\n2) Validate request\n    Nếu có lỗi xảy ra thì trả về status 040\n3) Check xem creatorId có tồn tại trong table creator hay không, nểu có thì đi tiếp bước 4, nếu không thì trả về status 011.\n4) Check xem trong table creator_onetime_auth đã tồn tại data có creatorId và token tương ứng hay chưa, nếu có thì xóa đi.\n4) Gen ra random code gồm 6 chữ số\n5) Tạo 1 record mới trong table creator_onetime_auth\n6) Thực hiện gửi SMS cho người dùng\n7) Tạo response trả về": "II）ステップ：\n1）リクエストをFormに変換\n2）リクエストをバリデーション（エラーがあればstatus 040を返す）\n3）creatorIdがcreatorテーブルに存在するか確認（存在すればステップ4へ、なければstatus 011を返す）\n4）creator_onetime_authテーブルにcreatorIdとtokenのデータがあれば削除\n4）6桁のランダムコードを生成\n5）creator_onetime_authに新しいレコードを作成\n6）SMSをユーザーに送信\n7）レスポンスを返す",
        "II) Câu sql:": "II）SQL文：",
        "Kiểu trả về": "返却型",
        "Loại": "種別",
        "creator.status = 10：退会 và ngày hiện tại > ngày cuối tháng 2 năm sau so với hạng mục cancel_approval_at": "creator.status = 10：退会　かつ現在日付　＞　 cancel_approval_at項目の日付より翌年の2月末日",
        "Loại validate": "バリデーションタイプ",
        "Message lỗi": "エラーメッセージ",
        "Method Name": "メソッド名",
        "Mô tả": "Description",
        "Mô tả Method xử lý chính": "主処理メソッドの説明",
        "Mô tả validate": "バリデーションの説明",
        "Name": "名前",
        "Params": "パラメータ",
        "QA về message": "メッセージに関するQA",
        "Review Comment": "Review Comment",
        "SQL Sử dụng": "使用するSQL",
        "Table name": "テーブル名",
        "Trạng thái": "Status",
        "Tên chức năng:": "機能名：",
        "Chức năng đăng ký nên ai cũng có thể truy cập": "登録機能のため、誰にもアクセスできる",
        "Validate request": "リクエストのバリデーション",
        "2) Validate request": "2) リクエストのバリデーション",
        "Nếu có lỗi xảy ra thì trả về status 040": "　エラーがある場合、404のステータスを返す",
        "Validate theo regexp": "正規表現によるバリデーション",
        "Ví dụ": "例",
        "- Validate số điện thoại": "電話番号のバリデーション",
        "Viết 1 class MobileNumberValidator để validate định dạng số điện thoại": "MobileNumberValidatorクラスを作成し、電話番号形式のバリデーションを行う",
        "Sử dụng class EmailValidator để validate những điều kiện sau": "EmailValidator クラスを使用して、以下の条件をバリデートする：",
        "Nhập số điện thoại và gửi sms cho người dùng": "電話番号を入力して、ユーザーにSMSで送信する",
        "1)có bao gồm ký hiệu @ hay không": "1）「@」記号が含まれているかどうか",
        "2)ký tự @ có đang ở đầu hay ở cuối hay không": "2）「@」記号が先頭または末尾にないかどうか",
        "3)maxlength 253ký tự": "3）最大長が253文字以内であること",
        "2) Xử lý": "２）対応",
        "- Tồn tại trong dữ liệu bảng master": "マスターテーブルにデータが既に存在しています",
        "Sử dụng class annotation để convert chữ số fullsize thành halfsize": "annotationクラスを利用して全角数字を半角数字に変換する",
        "2) Tạo response trả về :": "2) レスポンスの返却を作成：",
        "Đây là hàm có sẵn KH cung cấp": "これは顧客から提供された既存関数です",
        "Đăng nhập": "ログイン",
        "đã update vào coding design": "coding_designに反映済み",
        "- Validate bắt buộc nhập giá trị nếu thỏa mã điều kiện": "条件を満たす場合は、必須入力のバリデーションを行う",
        "- Convert full-width to half-width": "全角を半角に変換する",
        "- dữ liệu Tồn tại trong bảng master": "マスターテーブルにデータが存在することを確認する",
        "Viết 1 class HalfsizeNumberValidator để validate xem giá trị truyền vào có phải chứa toàn kí tự số halfsize hay không": "HalfsizeNumberValidatorクラスを作成し、 渡された値が全て半角数字かをバリデーションする",
        # FE
        "1) Mô tả requirement": "1) 要件概要",
        "2) Định nghĩa component": "2) コンポネント定義",
        "3) Định nghĩa hook, logic": "3) hook, logicの定義",
        "4) Các function dùng chung": "4) 共通関数",
        "1: Lưu thông tin cá nhân": "1: 個人情報を保存する",
        "6) Định nghĩa hạng mục": "6) 項目定義",
        "7) Sử dụng component common": "7) 共通コンポネントを利用する",
        "8) Định nghĩa event": "8) イベント定義",
        "9) Quản lý Q&A": "9) Q&A管理",
        "Tên hạng mục": "Item Name",
        "Tên Event": "Event Name",
        "Tài liệu requirement:": "要件定義書",
        "10) Quản lý bug": "10) バグ管理",
        "Sử dụng": "Use/Not use",
        "Chức năng": "Purpose",
        "* Lưu ý không chỉnh sửa component common": "※ Explain if mofidy common component",
        "Không phải xử lý": "対応不要",
        "Mô tả nếu chỉnh sửa component common": "共通コンポネントを修正すれば、記載",
        "Điều kiện validate": "バリデーション条件",
        "Phải là 4 ký tự số half size": "半角数字4桁であること",
        "Phải là 3 ký tự số half size": "半角数字3桁であること",
        "Phải là 7 ký tự số half size": "半角数字7桁であること",
        "Phải là 5 hoặc 6 ký tự số half size": "半角数字5又は6桁であること",
        "phải là ký tự số half size": "半角数字であること",
        "Có thể input bắt đầu từ ０": "0から入力可能とする",
        "Cho phép giá trị số bắt đầu từ ０": "0から入力可能とする",
        "Định dạng search": "検索形式",
        "Định dạng symbol": "symbol形式",
        "Định dạng numberWidth": "numberWidth形式",
        "Định dạng numberBranch": "numberBranch形式",
        "Định dạng account number": "account number形式",
        "Định dạng account holder": "account holder形式",
        "Phải input ký tự kana half size": "半角カタカナ文字で入力すること",
        "Quản lý và xử lý logic input": "インプットの管理・ロジック処理",
        "Quản lý và xử lý logic button": "ボタンの管理・ロジック処理",
        "Quản lý và xử lý logic select": "セレクトボックスの管理・ロジック処理",
        "Quản lý và xử lý logic textarea": "テキストエリアの管理・ロジック処理",
        "Quản lý và xử lý logic radio": "ラジオボタンの管理・ロジック処理",
        "Quản lý và xử lý logic checkbox": "チェックボックスの管理・ロジック処理",
        "Quản lý và xử lý logic chọn ngày tháng": "日付選択の管理・ロジック処理",
        "Quản lý và xử lý logic hiện thị message validate": "バリデーションメッセージ表示の管理・ロジック処理",
        "Quản lý và xử lý logic table": "テーブルの管理・ロジック処理",
        "Quản lý và xử lý logic phân trang": "ページネーションの管理・ロジック処理",
        "Quản lý và xử lý logic menu dropdown": "ドロップダウンメニューの管理・ロジック処理",
        "Quản lý và xử lý logic upload file": "ファイルアップロードの管理・ロジック処理",
        "modal quản lý việc logic chọn cơ quan tài chính": "金融機関選択モーダルのロジック管理",
        "modal quản lý việc logic và chọn chi nhánh tài chính": "金融支店選択モーダルのロジック管理",
        "Form điều khoản dịch vụ": "利用規約フォーム",
        "Form nhập thông tin account": "アカウント情報入力フォーム",
        "Component dùng lại hiển thị lý do trả lại": "返却理由表示の再利用コンポーネント",
        "Click vào button 選択する của trường Các tổ chức tài chính/金融機関 để hiển thị modal chọn cơ quan tài chính": "「金融機関」フィールドの「選択する」ボタンをクリックし、金融機関選択モーダルを表示する",
        "Search cơ quan tài chính trong modal: chọn bằng radio cơ quan tài chính tương ứng với tên ngân hàng đã input hoặc 金融機関コード(code cơ quan tài chính)": "モーダル内で金融機関を検索：入力された銀行名または金融機関コードに一致する金融機関をラジオボタンで選択する",
        "Button xác nhận/確定する tại modal cơ quan tài chính: đóng modal và back về màn đăng ký lại（ID:D-C-010）": "金融機関モーダルの「確定する」ボタンをクリックして、モーダルを閉じ、登録画面（ID:D-C-010）に戻る",
        "Click vào button 選択する của trường mã chi nhánh/支店コード để Hiển thị modal chọn chi nhánh": "「支店コード」フィールドの「選択する」ボタンをクリックし、支店選択モーダルを表示する",
        "Search tên chi nhánh trong modal chọn: Chọn bằng radio chi nhánh tương ứng với tên chi nhánh đã input": "モーダル内で支店名を検索：入力された支店名に一致する支店をラジオボタンで選択する",
        "Button xác nhận/確定する tai modal chi nhánh: đóng modal và back về màn đăng ký lại（ID:D-C-010）": "支店モーダルの「確定する」ボタンをクリックして、モーダルを閉じ、登録画面（ID:D-C-010）に戻る",
        "Button lưu nháp/ 下書き保存する: mở modal C-021 アカウント情報登録画面（下書き保存完了モーダル）và Điều hướng  về màn hình bảng điều khiển C-020 trước khi đăng ký (bao gồm dự thảo)/C-020 本登録前ダッシュボード画面（下書き有り）": "「下書き保存する」ボタンをクリックして、モーダル（C-021 アカウント情報登録画面：下書き保存完了）を表示後、本登録前ダッシュボード画面（下書き有り）C-020へ遷移する",
        "Button confirm nội dung input/入力内容を確認する điều hướng màn confirm thông tin chuyển khoản OK: C-027 口座情報不備時再登録確認画面": "「入力内容を確認する」ボタンをクリックして、C-027 口座情報不備時再登録確認画面へ遷移する",
        "Button Quay trở lại chỉnh sửa/編集に戻る Điều hướng tới C-026 口座情報不備時再登録画面": "「編集に戻る」ボタンをクリックして、C-026 口座情報不備時再登録画面へ遷移する",
        "Button đăng ký/登録する/ Điều hướng tới màn trước khi đăng ký chính thức（ID:D-C-007）": "「登録する」ボタンをクリックして、本登録直前画面（ID:D-C-007）へ遷移する",
        "Open modal chọn cơ quan tài chính": "金融機関選択モーダルを開く",
        "Search cơ quan tài chính": "金融機関を検索する",
        "Xác nhận chọn cơ quan tài chính": "金融機関の選択を確定する",
        "Open modal chọn chi nhánh tài chính": "金融機関の支店選択モーダルを開く",
        "Search chi nhánh tài chính": "支店を検索する",
        "Xác nhạn chọn chi nhánh tài chính": "支店の選択を確定する",
        "Lưu nháp": "下書き保存する",
        "Confirm nội dung vừa nhập thông tin tài khoản": "入力した口座情報を確認する",
        "Quay trở lại trang chỉnh sửa thông tin tài khoản": "口座情報編集画面に戻る",
        "Đăng ký": "登録する",
        "Đang hỏi": "確認中",
        "Đã apply vào coding design": "コーディング設計に適用済み",
        "Đã apply vào code": "コードに適用済み"
}